openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about diseases information"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Disease:
      type: "object"
      required:
        - name
      properties:
        name:
          type: string
        state:
          type: string
        cases:
          type: integer
        content:
          type: string
  parameters:
    name:
      name: "name"
      description: "Name of the disease"
      in: path
      required: True
      schema:
        type: "string"

    state:
      name: "state"
      description: "State information"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /disease:
    get:
      operationId: "disease.read_all"
      tags:
        - "Disease"
      summary: "Read the list of disease"
      responses:
        "200":
          description: "Successfully read disease list"
    post:
      operationId: "disease.create"
      tags:
        - Disease
      summary: "Create a disease information"
      requestBody:
        description: "Disease to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "disease"
              $ref: "#/components/schemas/Disease"
      responses:
        "201":
          description: "Successfully created the disease"
  /disease/{name}:
    get:
      operationId: "disease.read_one"
      tags:
        - Disease
      summary: "Read one disease"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read the disease"
    put:
      tags:
        - Disease
      operationId: "disease.update"
      summary: "Update the disease"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully updated disease"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Disease"
    delete:
      tags:
        - Disease
      operationId: "disease.delete"
      summary: "Delete the disease"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted the disease"
